### PR TITLE
bump version to -06

### PR DESCRIPTION
**Pull request by thomas-fossati**

### CODE REVIEW

**Review by yaronf — APPROVED** [review]
I think I said it before: with MT's makefile you don't need the version number in the markdown file, it can be generated automatically.

**Comment by thomas-fossati** [comment]
> I think I said it before: with MT's makefile you don't need the version number in the markdown file, it can be generated automatically.

We don't use MT's build machinery though.  We seem to be running on a custom-made toolchain.

**Comment by yaronf** [comment]
> > I think I said it before: with MT's makefile you don't need the version number in the markdown file, it can be generated automatically.
> 
> We don't use MT's build machinery though. We seem to be running on a custom-made toolchain.

You're right. The makefile is ridiculously simple (unlike MT's which is ridiculously complex).

**Review by muhammad-usama-sardar — APPROVED** [review]

**Comment by thomas-fossati** [comment]
> [...] The makefile is ridiculously simple

It looks like something I might have written :)

**Pull request merged**
